# Install requirements via apt....
sudo apt update ## Update repo info....
sudo apt install -y flatpak wget curl ## requirements via apt....

# Uninstall the "politically heated" firefox, thunderbird, and "stale" libreoffice... we will replace these later! ;)
sudo apt remove -y firefox ## Checks for the apt package...
sudo snap remove firefox ## Checks for the snap package...
sudo apt remove -y thunderbird ## Checks for the apt package...
sudo snap remove thunderbird ## Checks for the snap package...
sudo apt remove -y libreoffice* ## Checks for the apt package...
sudo snap remove libreoffice* ## Checks for the snap package... (for the future.)

# Update any existing flatpaks...
flatpak update ## update em all....

# Add flathub repo...
flatpak remote-add --user -y --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo ## the hub ;)

# Installs my essentials...
flatpak install --user -y com.obsproject.Studio com.protonvpn.www com.spotify.Client io.freetubeapp.FreeTube io.github.ec_.Quake3e.OpenArena io.gitlab.librewolf-community network.loki.Session org.darktable.Darktable org.ferdium.Ferdium org.flightgear.FlightGear org.kde.krita org.libreoffice.LibreOffice org.localsend.localsend_app org.pitivi.Pitivi org.videolan.VLC ## Install tons of stuff....

# Main gaming apps...
flatpak install --user -y com.valvesoftware.Steam ## Installs Steam (duh.)
flatpak install --user -y com.heroicgameslauncher.hgl ## For installing Epic Games alternative launcher "Heroic"

# Install Game Streaming Stuffs
flatpak install --user -y io.github.hmlendea.geforcenow-electron ## GFN

# Install Minecraft/ROBLOX
flatpak install --user -y org.prismlauncher.PrismLauncher ## Minecraft Java Launcher
flatpak install --user -y org.vinegarhq.Vinegar ## For using ROBLOX Studio
flatpak install --user -y https://sober.vinegarhq.org/sober.flatpakref ## Installs Sober Project to run ROBLOX Player on our Linux PC

# Install coding stuffs...
flatpak install --user -y org.filezillaproject.Filezilla # FTP/SFTP uploading program
flatpak install --user -y com.visualstudio.code # VSCode. It's a code editor, NOT an IDE.
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash # nvm, used to manage nodejs versions

# Install AI stuffs....
flatpak install --user -y org.upscayl.Upscayl
curl -fsSL https://ollama.com/install.sh | sh
