# Install requirements via apt....
sudo apt update ## Update repo info....
sudo apt install -y flatpak wget curl python3 python3-pip ## requirements via apt....

# Uninstall the "politically heated" firefox, thunderbird, and "stale" libreoffice... we will replace these later! ;)
sudo apt remove -y firefox ## Checks for the apt package...
sudo snap remove firefox ## Checks for the snap package...
sudo apt remove -y thunderbird ## Checks for the apt package...
sudo snap remove thunderbird ## Checks for the snap package...
sudo apt remove -y libreoffice* ## Checks for the apt package...
sudo snap remove libreoffice* ## Checks for the snap package... (for the future.)

# Update any existing flatpaks...
flatpak update ## update em all....

# Add flathub repo...
flatpak remote-add --user -y --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo ## the hub ;)

# Installs my essentials...
flatpak install --user -y com.obsproject.Studio com.protonvpn.www com.spotify.Client io.freetubeapp.FreeTube io.github.ec_.Quake3e.OpenArena io.gitlab.librewolf-community network.loki.Session org.darktable.Darktable org.ferdium.Ferdium org.flightgear.FlightGear org.kde.krita org.libreoffice.LibreOffice org.localsend.localsend_app org.shotcut.Shotcut org.videolan.VLC ## Install tons of stuff....

# Main gaming apps...
flatpak install --user -y com.valvesoftware.Steam ## Installs Steam (duh.)
flatpak install --user -y com.heroicgameslauncher.hgl ## For installing Epic Games alternative launcher "Heroic"

# Install Game Streaming Stuffs
flatpak install --user -y io.github.hmlendea.geforcenow-electron ## GFN

# Install Minecraft/ROBLOX
flatpak install --user -y org.vinegarhq.Vinegar ## For using ROBLOX Studio
flatpak install --user -y https://sober.vinegarhq.org/sober.flatpakref ## Installs Sober Project to run ROBLOX Player on our Linux PC. Note that this requires the "universal" mapk binary from [here.](https://www.apkmirror.com/apk/roblox-corporation/roblox/)

# Install coding stuffs...
flatpak install --user -y org.filezillaproject.Filezilla # FTP/SFTP uploading program
flatpak install --user -y com.visualstudio.code # VSCode. It's a code editor, NOT an IDE.
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash # nvm, used to manage nodejs versions

# Install AI stuffs....
flatpak install --user -y org.upscayl.Upscayl ## Install AI upscaler
curl -fsSL https://ollama.com/install.sh | sh ## Install AI chatbot

# SneedHosts (Got permission from the Sneed Group team to use this!)
printf "# SneedHosts Collection. Made by Sneed Group.\n" > sneedhosts.tmp ## Init the hosts with a line giving credit.
curl https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/pro.txt >> sneedhosts.tmp ## Get collection
printf "\n" >> sneedhosts.tmp ## New line
curl https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts >> sneedhosts.tmp ## Get collection
printf "\n" >> sneedhosts.tmp ## New line
curl https://someonewhocares.org/hosts/hosts >> sneedhosts.tmp ## Get collection
printf "\n # END OF SNEEDHOSTS" >> sneedhosts.tmp ## End Of File
sudo mv /etc/hosts /etc/hosts.bak ## Backup old hosts file...
sudo cp sneedhosts.tmp /etc/hosts ## ...and insert ours instead!

# Clear and ask for reboot.
clear ## Clear the screen.
echo "Done! PLEASE REBOOT NOW TO APPLY CHANGES." ## Asks for reboot.
